### ISSUE TITLE
Duplicate GATT service registrations (Herald)

### ISSUE THREAD

**Issue by jimmo** [AU-COVIDSafe/mobile-android#33]
Noticed this while running a built with the `herald` branch -- two different issues with the advertising start/stop mechanism that runs every 15 minutes that I think have the same root cause. cc @alwentiu who noticed the same thing.

a) Sometimes the app will startup in a way where every time the timer goes off, it appears that it never clears the previous service registrations. This is easy to see by connecting with any other BLE client (e.g. nRF Connect or bluez) and the discover service operation will return N copies of the `b82ab3fc-1595-4f6a-80f0-fe094cc218f9` service (where N = uptime-mins / 15).

When this happens, I see the same phone advertising on two RPAs at the same time.

b) If you disable then re-enable the Bluetooth interface on the phone while the app is running, it triggers the same behaviour. It's very easy to get to the point where the phone is advertising on several RPAs at the same time (i.e. many tens of Hz total of advertising beacons from the same phone). And after enough times it fails to start advertising.

Fortunately it appears that the RPAs continue to rotate, so this doesn't appear to be a privacy issue.

---

As well as leading to potential issues with advertising stopping working, this also causes nearby phones to think that there are more nearby phones that they need to connect to (thanks to the multiple RPAs) (note that they all have different pseudo addresses) and it also slows down tempid exchange because the service discovery step has to discover way more services than necessary. Both of these will lead to a decrease in contact tracing efficiency.

---

I think the underlying cause here is that it's very easy to get into a state where multiple copies of `AdvertLoopTask` are running. My suspicion is that `BluetoothMonitoringService.kt` calls `sensorStart()` more often than it needs to (both on startup and when it detects Bluetooth is enabled).

I think this is technically a COVIDSafe-implementation-of-Herald bug, but I'm going to raise it with Herald too because it shouldn't allow getting into this state.

**Comment by HendX** [comment]
It’s issues like these that should have been ringing alarm bells since March/April when this project began.

Both Apple and Google are hugely influential in defining and advancing Bluetooth standards. They know how to build reliable systems - they have huge teams and unparalleled expertise and resources to build such systems.

Additionally, Exposure Notifications are being used by hundreds of millions of users worldwide, so it has the install base to allow ongoing improvement and development, as has been seen with the additional feature drops in iOS 13.6 and 14 that provide a huge amount of adaptability to any single nation’s requirements.

**There is enough evidence with bugs like these and general ongoing reliability issues that you have to realise you (DTA) are completely out of your depth on this app.**

Please shut it down or switch to ENF. There is no third option that serves the needs of the Australian public.

**Comment by HendX** [comment]
Why the downvote? The lack of broad adoption or testing of COVIDSafe Herald is a real risk, especially given its past of being rejected in the UK even after a lengthy trial.

Additionally, @jimmo has previously pointed out that copying in a third party library file-by-file rather than referencing it as a dependency is also a risk.

This is a good example, since as #34 points out, the source trees have already deviated, given there are `kt` files in one and not the other.

**Comment by jimmo** [comment]
@covidsafe-support @covidsafe-team Please see https://github.com/vmware/herald-for-android/issues/107#issuecomment-744486501 -- I think this is a bug in Herald too.

**Comment by kodekoala247** [comment]
Looks like tester error. nRF Connect shows history of detected devices. Duplicate services linked to different addresses on same physical device. Is that even possible?

**Comment by alwentiu** [comment]
@jimmo  and I confirmed this bug independently, so it's unlikely a tester error. I have tested it on several devices running various versions of Android (8, 9, 10, and 11); all exhibit the same behaviour. Turning bluetooth on/off results in duplicate GATT services being created. The advertisements over multiple RPAs were observed not just using nRF connect, but also using Bluez bluetooth scanner (bluetoothctl), that's available in standard linux installations. The logcat outputs show clearly duplicates SSIDs are being registered. @covidsafe-team  if it helps with the debugging, I'm happy to share the logcat output privately, though I don't think that would be necessary as the issue is easily reproducible. 

Note that a consequence of the phone not being able to start the advertisement is that the phone can't work as a peripheral, so other phones will not be able to download the tempId from the affected phone. However, scanning still works. So the tempID exchange goes only one way.

**Comment by jimmo** [comment]
> Looks like tester error. nRF Connect shows history of detected devices.

@kodekoala247 Please see
https://github.com/vmware/herald-for-android/issues/107#issuecomment-745042378

> Duplicate services linked to different addresses on same physical device. Is that even possible?

Yes

**Comment by covidsafe-team** [comment]
Thanks @jimmo and @alwentiu - we are taking a close look at this one. Thanks for providing additional data @alwentiu .

**Comment by kodekoala247** [comment]
Confirmed tester error. Tools show history of adverts. Try connect to duplicates. Only one advert works for connect/read/write. Look at app logs on central, no duplicates. One physical device multiple working addresses? Doubtful.

**Comment by alwentiu** [comment]
@jimmo  @covidsafe-team  See the pull request related to this issue.
Credit to @jimmo  who has previously mentioned the potential root causes for this issue. The pull request is meant only to demonstrate Jim's diagnosis. More tests will be needed to confirm the fix.

**Comment by covidsafe-team** [comment]
Thank you @jimmo and @alwentiu for your assistance with this issue. We have implemented a fix into today's release of COVIDSafe. You can find the release notes here: https://www.dta.gov.au/news/covidsafe-uses-herald-protocol-improve-app-performance

**Comment by yaakov-h** [comment]
@covidsafe-team This is not fixed in the Google Play production release of the app (v2.0). I can still reproduce the duplicate services issue on my test phone - Samsung A20 SM-A205YN.

**Comment by jimmo** [comment]
@covidsafe-team I also continue to see this on my Pixel 2. I'm running a build from the `master` branch, but with no modifications other than to change `advertRefreshTimeInterval` to two minutes.

I still see both the multiple-RPA issue, and the duplicate service registrations (both with no user interaction, and also when powering off/on the Bluetooth adaptor).

> Thank you @jimmo and @alwentiu for your assistance with this issue.

You're welcome, but unfortunately you have not implemented the fixes that we suggested, either described here or in private correspondence when you reached out for more help.

In the initial bug report I said "My suspicion is that BluetoothMonitoringService.kt calls sensorStart() more often than it needs to (both on startup and when it detects Bluetooth is enabled).". @alwentiu 's PR (https://github.com/AU-COVIDSafe/mobile-android/pull/36) has a fix for this.

Additionally, on https://github.com/vmware/herald-for-android/issues/107#issuecomment-747902520 I called out that the Herald fix does not address the multiple advertising as it also needs to use stopAdvertising().

**Comment by jimmo** [comment]
I applied https://github.com/AU-COVIDSafe/mobile-android/pull/39 and it still doesn't fix the issue on the Pixel 2.

**Comment by covidsafe-team** [comment]
Thanks @alwentiu, @jimmo, @kodekoala247 and @HendX. We have prioritised this issue and #40 in our backlog. We'll provide an update on progress.

**Comment by jimmo** [comment]
This is still an issue in the play store build of COVIDSafe 2.1 released yesterday. I still see both the duplicate advertisements and the duplicate service registration.
